name = "Jl2Py"
uuid = "fe5dac85-8b54-4abc-b8de-3413e1fbc3b7"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1"
julia = "1.7"
