name = "Jl2Py"
uuid = "fe5dac85-8b54-4abc-b8de-3413e1fbc3b7"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.7"
